#!/bin/bash

if [ $# -ne 1 ]; then
    echo "please specify a test directory"
    exit
fi

if [ ! -d "$1" ]; then
    echo "invalid test directory"
    exit
fi

make clean
make
for filename in ${1}/*.qk; do
	echo
	echo $(basename $filename .qk)
    echo "===================="
	./quack $filename
    if [ -f ${PWD}/generated.c ]; then
        echo -n "Compiling: "
        make result
        echo ""
        ./compiled_quack
    fi
    rm -f ${PWD}/compiled_quack ${PWD}/generated.c
    echo "===================="
    echo ""
done
